chore: storybook 설정
TmaxFintech/corebank-demo-fe pull request #17
Opened 2024-07-03 07:31 UTC by LucetTin5

# Feature Request

👉 기능 설명

- storybook을 설치했습니다
- `Typography`, `Icon - Icon16, 24, Noti`, `Illustration`, `Bdage` 스토리를 생성했습니다
- `concurrently`를 설치했습니다
- `yarn dev:both`를 실행하면 dev서버와 스토리북 서버가 함께 실행됩니다 
- 각각 실행도 가능합니다

👉 요청 및 질문사항

- 요청 및 질문사항이 있다면 작성해 주세요

📷 스크린샷

![image](https://github.com/TmaxFintech/corebank-demo-fe/assets/75024621/b7b3410c-876e-417e-831b-205c7309f037)

2024-07-04 01:51 UTC, hi6724 requested changes

2024-07-04 01:51 UTC, hi6724 commented on src/shared/components/stories/Badge.stories.tsx
> +  decorators: [
ThemeProvider는 여기보다는 preview에 전역으로 추가하는게 편할 것 같습니다.

2024-07-04 01:51 UTC, hi6724 commented on .storybook/preview.ts
> +import type { Preview } from '@storybook/react';
`src/styles/global.css `
추가가 필요할 것 같습니다

2024-07-04 03:51 UTC, hi6724 approved these changes

2024-07-05 04:37 UTC, hwangsujoung approved these changes
👍

2024-07-05 05:12 UTC, merged