feat: Navigation
TmaxFintech/corebank-demo-fe pull request #25
Opened 2024-07-05 09:22 UTC by 0hhanum

# Feature Request

👉 기능 설명
- 내부 논의 내용대로 레이아웃만 작업했습니다.
- 동작 방식은 라우팅 방식 결정 후 추가 개발하는 게 맞는 수순인 것 같아 목데이터로 임시방편 처리했습니다. 

1. GNB, LNB를 포함하는 `<Layout>` 컴포넌트를 최상위에 배치했습니다.
2. `LNBMenuItem`, `LNBSubMenuItem` 등의 컴포넌트 이름은 최대한 피그마 기반으로 명명했습니다.

👉 요청 및 질문사항
- 요구 스펙이 명확하지 않은 부분들이 있어 피그마로 소통중입니다.

📷 스크린샷

- 간단한 스크린샷을 첨부해주세요
![스크린샷 2024-07-05 오후 5 54 49](https://github.com/TmaxFintech/corebank-demo-fe/assets/79507291/e2a6b3c4-d204-46c4-a4cf-b6a35070c2d4)

2024-07-08 01:15 UTC, hi6724 requested changes
![image](https://github.com/TmaxFintech/corebank-demo-fe/assets/68803719/67e3dab0-97b8-4c6b-8f43-1563643669b6)

LNB의 우측에 칩같은 부분은 혹시 어떤식으로 사용할 수 있을까요?
subMenu가 active상태면 부모 menu는 active가 아닌거 처럼 피그마에는 그려져있는데, 개발하신 코드에는 부모도 active상태인 것 같아요. 혹시 이 부분은 ux분과 논의가 된건가요?
화면에서 LNB가 없는 화면이 없는데 LNB에 isVisible속성은 어떤 페이지에서 사용하려고 만드신건가요?

2024-07-08 01:15 UTC, hi6724 commented on src/shared/components/layouts/navs/LNBs/LNBMenuItem.tsx
> +  height: 52px;
피그마랑 조금 다른 부분이 있는 것 같습니다
피그마는 총 height 56px 이고, 안에 48px의 content가 있는 형태인 것 같습니다.

2024-07-08 01:15 UTC, hi6724 commented on src/shared/components/layouts/navs/LNBs/LNBSubMenuItem.tsx
> +  height: 48px;
여기도 피그마랑 조금 다른 것 같은데 확인해주세요.
height 와 padding-left가 조금 다른 것 같습니다

2024-07-08 03:43 UTC, 0hhanum commented
@hi6724 
1. `MenuItem`, `SubMenuItem`의 Active 상태
	Active 상태 관련 정책이 명시되지 않았는데 제가 너무 나이브하게 진행했네요.
	해당 부분 조율 진행중입니다. 수정 후 노티 드리겠습니다.

2. `SubMenuItem` 칩
	 컴포넌트 예시에는 있지만
	 어떤 상황에 사용되는지, 칩의 종류가 고정인지 등의 정책은 추후 화면 기획에서 정해질 거 같아 
	 추후 라우팅 시스템 구현 시 같이 고려해야 하지 않을까 생각했습니다. 

	`SubMenuItem`이 children을 받는 형태라  
      ```tsx
      LNBAccordian.tsx
      ...
      {subMenus.map(subMenu => (
      <LNBSubMenuItem key={subMenu} isActive={currentSubMenu === subMenu}>
      {subMenu}
      <NotificationIcon size="24" type="caution" /> // 칩 예시
      </LNBSubMenuItem>
      ))}
      ...
      ```
    routes 정보에 상품 등록 status를 추가해 위와 비슷한 방식으로 구현할 수 있을 거 같은데 혹시 더 좋은 방법이 있다면 제안해주시면 감사하겠습니다 !
 
    ![image](https://github.com/TmaxFintech/corebank-demo-fe/assets/79507291/6f1b1ac7-aa2d-44e8-b059-d4813b65f980)
    

3. `isVisible` 
	추후에 접는 기능이 추가되지 않을까 해서 달아뒀습니다.

4.  디자인 관련
	확인해 주신 부분 수정했습니다.

제가 놓친 부분이 많았네요. 꼼꼼하게 확인해주셔서 감사합니다.

2024-07-08 03:43 UTC, 0hhanum commented on src/shared/components/layouts/Layout.tsx
> +    </SLayout>
부모 레이아웃 내 LNB와 컨텐츠가 놓인다고 생각했는데 말씀 주신 것처럼 `Container`가 없어도 되겠네요. 
margin-left로 처리한 이유는,,, 없어요😅 수정했습니다.

2024-07-08 03:43 UTC, 0hhanum commented on src/shared/components/layouts/navs/LNBs/LNBMenuItem.tsx
> +  border-radius: ${({ theme }) => theme.radius.radius120};
`MenuItem`은 `radius120`, `SubMenuItem`은 `radius80으로` 확인했습니다. 
그런데 `SubMenuIte`에도`radius120` 줬네요..😂 
수정했습니다.

2024-07-08 03:45 UTC, 0hhanum commented on src/shared/components/layouts/navs/LNBs/LNBMenuItem.tsx
> +  height: 52px;
height: 56px
content: 52px
로 확인했는데 맞을까요? 잘못되어있어서 수정했습니다.

2024-07-08 04:10 UTC, hi6724 commented
고생하셨습니다~!
GNB도 피그마에 맞춰서 수정해주세요!

2024-07-08 06:52 UTC, hi6724 approved these changes

2024-07-08 07:19 UTC, 0hhanum commented
@hi6724 
상위, 하위 메뉴 active 상태 조율 후 수정했습니다. 
제 짐작대로 한 부분이 틀렸었네요. 감사합니다.

2024-07-09 07:23 UTC, kimsh322 commented
고생하셨습니다!👍

2024-07-09 07:24 UTC, jaeyoung-tmax commented on src/shared/components/layouts/navs/GNB.tsx
> +  padding: 0 60px;
![스크린샷 2024-07-09 오후 4 24 12](https://github.com/TmaxFintech/corebank-demo-fe/assets/152590191/dd181495-d564-454f-a96f-a2b8855b53c1)
화면 줄어들면 줄바뀜 됩니다!
`padding`보다는 `width`로 크기 조절하면 좋을 것 같습니다

2024-07-09 08:19 UTC, 0hhanum commented on src/shared/components/layouts/navs/GNB.tsx
> +  padding: 0 60px;
> 0709 UX 문의내역
  Q) GNB MenuItem 내에 세 글자 이상의 메뉴가 들어올 시 좌우여백 60px 때문에 width 150px가 깨지게 되는데 어느 속성 우선시 해야하는지 문의드립니다!
  A) 텍스트에 따른 가변 넓이를 기준으로 해주시면 됩니다. 현재 GNB엔 모두 2자이기에 150Px이 된거라 고정값은 아닙니다. 
  추후에는 "상품팩토리" 등 보다 긴 텍스트가 쓰일 수 있겠지만 감안할 수 있는 차이고, 
  아직 IA가 확정이 아니고, GNB 넓이의 최대값도 정하진 않았지만 앞으로도 지나치게 긴 텍스트가 생기는 경우는 없도록 하겠습니다.
  
너비 고정이 아니라고 답변받아 `padding` 60px 기준으로 줄바꿈 발생 없도록 nowrap 적용했습니다.

2024-07-09 08:46 UTC, jaeyoung-tmax approved these changes

2024-07-09 09:27 UTC, 0hhanum commented
@jaeyoung-tmax 
구두 논의한대로

LNB - 아코디언 애니메이션, hover 효과
GNB - hover 효과 

UX 문의 후 수정사항 적용하였습니다 ! 확인 후 이모지 남겨주시면 머지하겠습니다.

2024-07-10 01:26 UTC, merged