feat: Calendar / CalendarDropdown
TmaxFintech/corebank-demo-fe pull request #41
Opened 2024-07-12 05:04 UTC by LucetTin5

# Feature Request

👉 기능 설명

- Calendar 컴포넌트는 보다 용도 명확하게 DatePicker 컴포넌트로 생성했습니다.
- InputField와 유사하나 다른 부분도 있고, 인풋필드를 너무 키우는것보단 분리하는 방향으로 제작했습니다.
- Calendar 관련 로직으로만 쓰이는 훅은 캘린더 아래의 훅으로 두었습니다
- react-hook-form 관련 적용은 아직 하지 않았습니다.
- DatePicker의 status는 InputField의 사용을 참고하여 외부에서 prop으로 넘기게 설정했습니다.
- CalendarDropdown은 현재 아래로만 열리게 되어있습니다 -> 뷰에 따라 위로 열리게도 해야될까요?
- global.css가 제거되고 생긴 GlobalStyles를 storybook/preview에 추가했습니다

👉 요청 및 질문사항

- 요청 및 질문사항이 있다면 작성해 주세요

📷 스크린샷

![image](https://github.com/user-attachments/assets/9abfd22d-4700-4b3e-b381-fb0f222aea59)
![image](https://github.com/user-attachments/assets/bf2c94b1-ffb9-4a05-8be1-55755f029a6b)

2024-07-15 04:12 UTC, IRONDESK commented
이번달 이전의 날을 선택한 뒤, 다시 input을 눌러서 picker를 호출하면 이번달이 보여지는데 선택된 달이 달력이 보여지는게 자연스러울 것 같습니다.

아래를 예시로 들자면, "2021년 6월 30일"을 선택 및 확인 한 뒤 다시 input을 선택했을 때 이번달 달력이 아닌 2021년 6월 달력이 보여지는 것을 말씀드린 것입니다!

![스크린샷 2024-07-15 오후 1 11 08](https://github.com/user-attachments/assets/8fff6405-5064-4b2c-bbf3-015e32eb9e6a)

2024-07-15 04:14 UTC, LucetTin5 commented
> 이번달 이전의 날을 선택한 뒤, 다시 input을 눌러서 picker를 호출하면 이번달이 보여지는데 선택된 달이 달력이 보여지는게 자연스러울 것 같습니다.
> 
그러네요 선택된 날짜가 다시 보이는게 맞는데 고려를 못했네요

2024-07-16 01:21 UTC, IRONDESK approved these changes

2024-07-16 03:56 UTC, hi6724 requested changes
1. DatePicker에서 선택된 값을 결국 상위 페이지에서 사용해야 할 텐데, onChange나 onSelect같은 값들이 필요하지 않을까요?

2. n월 n일을 선택하면 n월 n-1일이 선택되는 것 같은데, 저만 그런걸까요?!

3. 피그마에는 오늘날짜보다 이전 날짜의 색을 다르게 한 것 같은데 구현된 코드와는 조금 상이한 것 같습니다.

2024-07-16 03:56 UTC, hi6724 commented on src/shared/components/calendar/DatePicker.tsx
> +  const [dateValue, setDateValue] = useState(defaultValue ?? '');
부모에게 받은 defaultValue가 변경될 때 setDateValue를 해주어야 하지 않을까요?
예를 들면, API 호출 후 응답 값으로 defaultValue를 설정하고, disabled하는 경우가 있을 것 같습니다

2024-07-16 04:11 UTC, LucetTin5 commented
> 1. DatePicker에서 선택된 값을 결국 상위 페이지에서 사용해야 할 텐데, onChange나 onSelect같은 값들이 필요하지 않을까요?
> 2. n월 n일을 선택하면 n월 n-1일이 선택되는 것 같은데, 저만 그런걸까요?!
> 3. 피그마에는 오늘날짜보다 이전 날짜의 색을 다르게 한 것 같은데 구현된 코드와는 조금 상이한 것 같습니다.

1. RHF를 통한 연결을 진행할 것 같은데 해당 처리를 고려해서 추가하겠습니다.
2. ISOString 전환시에 문제가 생기네요..!
3. 이전/다음달인 경우는 회색 이번달은 검은색이되 오늘인 경우는 primaryNormal인데 이것 말고 다른 처리가 있나요?
![image](https://github.com/user-attachments/assets/edd0def0-0081-40ce-86a1-752e28a9e760)

2024-07-16 04:20 UTC, hi6724 commented
> 3. 이전/다음달인 경우는 회색 이번달은 검은색이되 오늘인 경우는 primaryNormal인데 이것 말고 다른 처리가 있나요?

코맨트를 너무 이상하게 달았네요..! 죄송합니다

제가 피그마를 보고 이해한내용은, 범위로 선택할 때 이전 선택값보다 이전 날짜를 회색으로 처리하는거로 이해했습니다.

![image](https://github.com/user-attachments/assets/935d9e2f-28c3-4e81-be16-b8b9f9bb5c53)

이번달과 저번달을 기준으로 하는게 아니라 이전에 선택된 특정 값을 기준으로 그 값보다 이전 값을 회색처리하고 선택할 수 없도록 하도록 이해했는데, 혹시 잘못 이해한걸까요?

2024-07-16 04:27 UTC, LucetTin5 commented
이전날짜는 disabled한다 이 내용 말씀일까요?
startDate가 있는 경우 그 이전의 선택만 막아놓고 색 처리는 안했는데 피그마에 코멘트 남겨봐야겠네요

2024-07-16 04:36 UTC, 0hhanum reviewed
1. 외부에서 `dateValue` 에 접근하는 방식
	- `DatePicker`를 사용하는 컴포넌트에 날짜 상태를 두고 `onSelect`를 전달해 `updateDateValue`에서 호출하는 방식으로 적용될까요? 
	- (개인적인 궁금증) 셀렉된 값을 외부에서 사용해야 하는 컴포넌트 특성 상 내부제어가 과연 필요한가 고민되는데 dateValue, onSelect 모두 외부에서 받는 방식은 어떻게 생각하시는 지 궁금해요.

2024-07-16 04:36 UTC, 0hhanum commented on src/shared/components/calendar/CalendarDate.tsx
> +const CalendarDate = forwardRef<HTMLDivElement, DateProps>(({ dateType, date, selected, disabled, onSelect }, ref) => {
`forwardRef` 사용 이유가 궁금합니다.

2024-07-16 04:36 UTC, 0hhanum commented on src/shared/components/calendar/DatePicker.tsx
> +            onMouseLeave={handleMouseLeaveOnError}
DatePicker 에러 메세지가 `hover`시에만 노출되는 건 공통 컴포넌트 중 Calendar에만 적용된 부분인가요?

2024-07-16 04:36 UTC, 0hhanum commented on src/shared/components/calendar/CalendarDropdown.tsx
> +                  selected={selectedDate.date === date && isCurrentMonth}
`selectedDate`와 비교하고 있어서

ex) 7.16일 select 후 OK -> `CalendarDropdown` 재 오픈 후 다른 달로 넘어갔다 오면 `selectedDate.date`가 초기화되어 
OK 설정한 날짜에 마킹이 안되는데 기획상 원래 이런걸까요?

2024-07-16 04:53 UTC, LucetTin5 commented on src/shared/components/calendar/DatePicker.tsx
> +            onMouseLeave={handleMouseLeaveOnError}
이부분은 이게 맞지 않나 하고 해버린 부분이라 문의 남기도록 하겠습니다.

2024-07-16 04:55 UTC, LucetTin5 commented
> 1. 외부에서 `dateValue` 에 접근하는 방식
>    
>    * `DatePicker`를 사용하는 컴포넌트에 날짜 상태를 두고 `onSelect`를 전달해 `updateDateValue`에서 호출하는 방식으로 적용될까요?
>    * (개인적인 궁금증) 셀렉된 값을 외부에서 사용해야 하는 컴포넌트 특성 상 내부제어가 필요한가 고민되는데 dateValue, onSelect 모두 외부에서 받는 방식은 어떻게 생각하시는 지 궁금해요.

외부 구조가 어떻게 될지 몰라 우선 DatePicker에 둔 형태이기는 합니다. <DatePicker {...register(name)} />를 고려해서 구조를 좀 변경하는게 맞을 것 같습니다.

2024-07-16 04:55 UTC, 0hhanum commented on src/shared/components/calendar/CalendarDate.tsx
> +  );
`<StyledDate />`가 `onClick`을 받고 있어서
`<HiddenRadio />`의 `onChange`은 불필요해 보이는데 제가 놓치고 있는 부분이 있을까요?

```tsx
      <HiddenRadio
        type="radio"
        aria-hidden="true"
        name="date"
        value={date}
        checked={selected}
        disabled={disabled}
        readOnly
      />
```

`onChange`를 빼고 `readOnly`를 추가하는 건 어떨까요.

추가) `type="radio"`는 `onChange`가 안 먹는다고 합니다. input 태그의 값이 변경되는 게 아니라 checked 상태가 변경되서 그렇다네요. 저는 이번에 알았네요.

2024-07-16 04:56 UTC, LucetTin5 commented on src/shared/components/calendar/CalendarDate.tsx
> +  );
HiddenRadio에 뭔가 처리를 하려다가 빼먹은 부분인 것 같습니다. 지금 value값이 input과 관련없이 움직이고 있어서 해당부분 삭제하도록 하겠습니다

2024-07-16 04:59 UTC, LucetTin5 commented on src/shared/components/calendar/CalendarDate.tsx
> +const CalendarDate = forwardRef<HTMLDivElement, DateProps>(({ dateType, date, selected, disabled, onSelect }, ref) => {
Date부터 위로 올라가면서 작업하는 과정에 필요할까 하고 일단 넣어놓고 시작했던 부분입니다.
삭제하도록 하겠습니다.

2024-07-16 05:05 UTC, LucetTin5 commented on src/shared/components/calendar/CalendarDropdown.tsx
> +                  selected={selectedDate.date === date && isCurrentMonth}
이건 남아있는 게 맞을 것 같기는 합니다.

2024-07-22 01:58 UTC, hi6724 approved these changes
고생하셨습니다~!

2024-07-22 02:01 UTC, merged